name: Publish package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    if: github.repository == 'vue3-plugins/vue3-katex'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
      - run: yarn install
      - run: yarn prerelease
      - run: npm publish --provenance --ignore-scriptse
